spring:
  profiles:
    include: db
  datasource: #mysql
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa: #jpa
    database: mysql #mysql
    database-platform: org.hibernate.dialect.MySQLDialect #방언 mysql 설정
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #테이블 엔티티 매핑시 소문자로 변환되는 것 막아줌 -> @Table에 적은대로 entity 매핑
  data :
    mongodb:
      host: 211.218.1.46
      port: 27017
      username: k0905sh
      password: tjdGUS123~!
      database: my_home
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging.level:
  org.hibernate.SQL: debug

server:
  port: 9999

gov :
  service :
    key : 5TNF1XMQwRcgHri+3ukTRRSzwiUJnr5JP7SBMUscTWORWs3skuuyM3YfJZpXzUD+dE6ITSrQb1YJb29HHNEzng==
