spring:
  profiles:
    include: db
  data:
    mongodb :
      auto-index-creation: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql #mysql
    database-platform: org.hibernate.dialect.MySQLDialect #방언 mysql 설정
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #테이블 엔티티 매핑시 소문자로 변환되는 것 막아줌 -> @Table에 적은대로 entity 매핑
    properties:
      hibernate :
        show_sql: true
        format_sql: true
        use_sql_comments: = true
        jdbc:
          batch_size: 100
          batch_versioned_data: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # for swagger
  # Spring boot 2.6버전 이후에 spring.mvc.pathmatch.matching-strategy 값이
  # ant_apth_matcher에서 path_pattern_parser로 변경되면서 몇몇 라이브러리에서 오류가 발생하기 때문이므로


#ant_path_matcher
#logging.level:
#  org :
#    hibernate.SQL: debug
logging:
  file:
    path: /home/k0905sh/Logs/my-home
  level:
    root: info
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate : DEBUG
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 10

server:
  port: 9019


gov :
  service :
    key : 5TNF1XMQwRcgHri+3ukTRRSzwiUJnr5JP7SBMUscTWORWs3skuuyM3YfJZpXzUD+dE6ITSrQb1YJb29HHNEzng==

