spring:
  profiles:
    include: db
  data:
    mongodb :
      auto-index-creation: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql #mysql
    database-platform: org.hibernate.dialect.MySQLDialect #방언 mysql 설정
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #테이블 엔티티 매핑시 소문자로 변환되는 것 막아줌 -> @Table에 적은대로 entity 매핑

    properties:
      hibernate :
        show_sql: true
        format_sql: true
        use_sql_comments: = true
        jdbc:
          batch_size: 100
          batch_versioned_data: true
  # for swagger
  # Spring boot 2.6버전 이후에 spring.mvc.pathmatch.matching-strategy 값이
  # ant_apth_matcher에서 path_pattern_parser로 변경되면서 몇몇 라이브러리에서 오류가 발생하기 때문이므로
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#ant_path_matcher
#logging.level:
#  org :
#    hibernate.SQL: debug
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate : DEBUG

server:
  tomcat:
    threads:
      max: 200
      min-spare: 10 # 활성화 상태로 유지할 최소 쓰레드의 개수
#    accept-count: 100 #모든 스레드가 사용 중일때 들어오는 연결 요청 큐의 최대 길이
  port: 9879


gov :
  service :
    key : 5TNF1XMQwRcgHri+3ukTRRSzwiUJnr5JP7SBMUscTWORWs3skuuyM3YfJZpXzUD+dE6ITSrQb1YJb29HHNEzng==

